export default [
  {
    iconText:'概览',
    iconImgShow:'/static/images/overview_selected_icon@2x.png',
    iconImgHide:'/static/images/overview_unselected_icon@2x.png',
    iconRouter:'/Index/overview',
    code:1,
  },
  {
    iconText:'用户管理',
    iconImgShow:'/static/images/Combined Shape@2x.png',
    iconImgHide:'/static/images/yonghuguanli_unselected_icon@2x.png',
    iconRouter:'/Index/userList',
    code:2,
  },
  {
    iconText:'应用列表',
    iconImgShow:'/static/images/list_selected_icon@2x.png',
    iconImgHide:'/static/images/list_unselected_icon@2x.png',
    iconRouter:'/Index/applicationList',
    code:3,
  },
  {
    iconText:'人脸分组管理',
    iconImgShow:'/static/images/management_selected_icon@2x.png',
    iconImgHide:'/static/images/management_unselected_icon@2x.png',
    iconRouter:'/Index/faceList',
    code:4,
  },
  {
    iconText:'设备管理',
    iconImgShow:'/static/images/management-facility-icon@2x.png',
    iconImgHide:'/static/images/management-facility-icon@2x_1.png',
    iconRouter:'/Index/equipmentList',
    code:5,
  },
  {
    iconText:'监控报表',
    iconImgShow:'/static/images/report_selected_icon@2x.png',
    iconImgHide:'/static/images/report_unselected_icon@2x.png',
    iconRouter:'/Index/statement',
    code:6,
  },
  {
    iconText:'技术文档',
    iconImgShow:'/static/images/document_selected_icon@2x.png',
    iconImgHide:'/static/images/document_unselected_icon@2x.png',
    iconRouter:'/Index/TCFApiList',
    code:7,

  },
  {
    iconText:'接入须知',
    iconImgShow:'/static/images/xuzhi_selected_icon@2x.png',
    iconImgHide:'/static/images/xuzhi_unselected_icon@2x.png',
    iconRouter:'/Index/instructionsList',
    code:8,

  },
  {
    iconText:'操作日志',
    iconImgShow:'/static/images/operation_selected_icon@2x.png',
    iconImgHide:'/static/images/operation_unselected_icon@2x.png',
    iconRouter:'/Index/log',
    code:9,
  },


  {
    iconText:'栏目管理',
    iconImgShow:'/static/images/lanmuguanli_selected_icon@2x.png',
    iconImgHide:'/static/images/lanmuguanli_unselected_icon@2x.png',
    iconRouter:'/Index/categories',
    code:10,
  },
  {
    iconText:'图文编辑',
    iconImgShow:'/static/images/tuwenbianji_selected_icon@2x.png',
    iconImgHide:'/static/images/tuwenbianji_icon@2x.png',
    iconRouter:'/Index/productlist',
    code:11,
  },
  {
    iconText:'SDK下载',
    iconImgShow:'/static/images/download_selected_icon@2x.png',
    iconImgHide:'/static/images/download_unselected_icon@2x.png',
    iconRouter:'/Index/SDKDownload',
    code:12,
  },
]
